### ISSUE TITLE
How to validate a list of strings

### ISSUE THREAD

**Issue by coders-kitchen** [valiktor/valiktor#25]
Hi

I'm currently building an API that accepts a list of Strings. And struggling at the moment on validating that the strings match a given pattern. And at most N are set.

Checking the length is easy

But how can I do the following:

```
data class Sample(val testData: List<String>) {

  init {
    validate(this) {
      validate(Sample::testData).hasSize(max = 2). ... ? Here I want to validate that the strings match a certain pattern
    }
  }
}
```

Would I have to write my own validator?

Best
Peter

**Comment by rodolphocouto** [comment]
Hi Peter,

Unfortunately that is not supported yet, so you have to write a custom validator.

We will work to improve support for collections of std lib types.

**Comment by phamthaibaoduy** [comment]
I'm facing same problem.

I have already written a custom validation function for my data type, but it's usable only for property. 

No support for using it inside `.validateForEach` 😢 

```kotlin 
fun <E> Validator<E>.Property<MyDataType?>.myCustomeValidation(): Validator<E>.Property<MyDataType?> 
```

**Comment by coders-kitchen** [comment]
Hi,

got it. I've written a custom validator for this now.

👍 for making extensions easy here. Way simpler than with the setup of javax validation.
