### ISSUE TITLE
Does the library supports ktor framework?

### ISSUE THREAD

**Issue by LeonDevLifeLog** [valiktor/valiktor#27]
## Is your feature request related to a problem? Please describe.
i use valiktor with ktor framework,i use it to check client request params when i call `call.receive<UserLoginRequest>()` function to receive an invalidate param,it not throw a ConstraintViolationException.
## Describe the solution you'd like
I expect it to throw an exception when i call `call.receive<UserLoginRequest>()` function with an invalidate request param.

## Describe alternatives you've considered
may be this library not support ktor framework.

## Additional context
``` kotlin
data class UserLoginRequest(val username: String, val password: String) {
    init {
        validate(this) {
            validate(UserLoginRequest::username).hasSize(6, 20)
            validate(UserLoginRequest::password).hasSize(6, 16)
        }
    }
}
```

**Comment by rodolphocouto** [comment]
Hi,

Which JSON binding library are you using with Ktor? Maybe that library is throwing another exception to wrap `ConstraintViolationException`.

Valiktor doesn't support Ktor natively yet, but you can write your own exception handlers to make the HTTP responses.

Do you have a sample project using Ktor + Valiktor? Maybe I can help you with that :)

**Comment by LeonDevLifeLog** [comment]
Gson library. this is sample project [shop-api](https://github.com/LeonDevLifeLog/shop-api)

**Comment by LeonDevLifeLog** [comment]
I use Gson library, there is a sample project
[shop-api(branch:feature/valiktor)](https://github.com/LeonDevLifeLog/shop-api/tree/feature/valiktor)

**Comment by LeonDevLifeLog** [comment]
ktor with gson not working，but ktor with kotlinx.serialization is working。
[Shop-api(branch: feature/kotlinx.serialization)](https://github.com/LeonDevLifeLog/shop-api/tree/feature/kotlinx.serialization?files=1)

**Comment by rodolphocouto** [comment]
Gson doesn't interpret Kotlin primary constructors properly, as described [here](https://stackoverflow.com/a/39963353).

I recommend you to use kotlinx.serialization or Jackson as JSON library.

I'm closing this issue for now, if you have any question, let me know.
