### ISSUE TITLE
Additional documentation when using testing with Spring @WebMvcTest

### ISSUE THREAD

**Issue by LtTempletonPeck** [valiktor/valiktor#28]
Is there any documentation on using valiktor with `@WebMvcTest` based Spring tests?

I've added `@Import(ValiktorAutoConfiguration::class, ValiktorWebMvcAutoConfiguration::class)` but it doesn't seem to use the valiktor constraint violation exception handlers.

**Comment by rodolphocouto** [comment]
Hi @LtTempletonPeck,

I assume that you are using `MockMvc` to write your tests, right? So you must define the Valiktor exception handlers as controller advice, like this:

```kotlin
val constraintViolationExceptionHandler = ConstraintViolationExceptionHandler(ValiktorConfiguration())
val invalidFormatExceptionHandler = InvalidFormatExceptionHandler(constraintViolationExceptionHandler)
val missingKotlinParameterExceptionHandler = MissingKotlinParameterExceptionHandler(constraintViolationExceptionHandler)

val mockMvc = MockMvcBuilders
    .standaloneSetup(YourControllerHere())
    .setControllerAdvice(
        constraintViolationExceptionHandler,
        invalidFormatExceptionHandler,
        missingKotlinParameterExceptionHandler
    )
   .setMessageConverters(...)
   .build()
```

There is an example [here](https://github.com/valiktor/valiktor/blob/master/valiktor-spring/valiktor-spring/src/test/kotlin/org/valiktor/springframework/web/controller/ExceptionHandlerFixture.kt#L99).

**Comment by rodolphocouto** [comment]
I'm closing this issue for now. If you have any other questions, feel free to open new issues.
